# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rndorg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: testing
service: email-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
  - Effect: Allow
    Action: 
      - ses:*
    Resource: '*'

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: send-email
          method: post
          cors: true
          

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

resources:
  Resources:
    EmailFunctionIAMRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service: 
                - lambda.amazonaws.com
                - apigateway.amazonaws.com
                
              Action: sts:AssumeRole
        Policies:
          - PolicyName: SendEmailPolicy
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - ses:SendEmail
                  Resource: "*"
