# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: rndorg
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: testing
service: email-service


provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"

plugins:
  - serverless-offline

functions:
  sendEmail:
    handler: handler.sendEmail
    events:
      - http:
          path: send
          method: post

package:
  patterns:
    - '!node_modules/**'
    - 'node_modules/aws-sdk/**'
    